<h3>RBS</h3>
<div class='rbs-sidebar-ul'>
  <ul>
    <li><a href='#'> residents</a>
      <ul>
        <li><a href='#'>add resident</a></li>
      </ul>
    </li>
    <li><a href='#'>blocks</a> <ul>
        <li><a href='#'>block 2</a></li>
        <li><a href='#'>block 3</a></li>
        <li><a href='#'>block 4</a></li>
        <li><a href-'#'>block 5</a></li>
        <li><a href='#'>block 6</a></li>
      </ul>       
    </li>
  </ul>
</div>
