<!DOCTYPE html>
  <head>
    <title>RH RBS</title>
    <link href="./static/default.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class= 'login-box'>
      <h3>RBS</h3>
      <form action ='/login' method='POST' >
        <table>
          <tr><td>matric </td><td><input type='text' name = 'user_name' /></td></tr>
          <tr><td>password </td><td><input type ='password' name = 'user_pass' /></td></tr>
          <tr><td></td><td><input type = 'submit' value ='Login' ></td></tr>
        </table>
      </form>
    </div>
  </body>
</html>
