<h4> Add a new resident </h4>
<form action ='./add_resident' method = 'POST' >
<table id='rbs_res'>
  <tr><td>Matric</td><td><input type = 'text' name = 'res_matric' /></td></tr>
  <tr><td>Name</td><td><input type = 'text' name = 'res_name' /></td></tr>
  <tr><td>Gender</td><td><select name='res_gender'><option>M</option><option>F</option></select></td></tr>
  <tr><td>Points</td><td><input type = 'text' name = 'res_point' /></td></tr>
  <tr><td>Email</td><td><input type = 'text' name = 'res_email' /></td></tr>
  <tr><td>Password</td><td><input type = 'password' name = 'res_pass'></td></tr>
  <tr><td>User Group</td><td><select name='res_group'><option>user</option><option>admin</option></select>
  <tr><td></td><td><input type = 'submit' value = 'Add' /></td></tr>
</table>

