<h2> Add New Resident </h2>
<form action ='/add_resident' method = 'POST' >
<table>
  <tr><td>Matric</td><td><input type = 'text' name = 'res_matric' /></td></tr>
  <tr><td>Name</td><td><input type = 'text' name = 'res_name' /></td></tr>
  <tr><td>Gender</td><td><input type = 'text' name = 'res_gender' /></td></tr>
  <tr><td>Points</td><td><input type = 'text' name = 'res_point' /></td></tr>
  <tr><td>Email</td><td><input type = 'text' name = 'res_email' /></td></tr>
  <tr><td>Password</td><td><input type = 'password' name = 'res_pass'></td></tr>
  <tr><td></td><td><input type = 'submit' value = 'Add' /></td></tr>
</table>

